replicaCount: 2

image:
  repository: skullpion91/tictactoe
  tag: latest

service:
  type: ClusterIP
  port: 80

# values.yaml
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "80"
  prometheus.io/path: "/metrics"
